### PR TITLE
Fix to_xml()

### PR DESCRIPTION
**Pull request by AlexNik**

### CODE REVIEW

**Comment by AlexNik** [comment]
I don't why GitHud can't reopen this PR https://github.com/andr1an/nic-api/pull/19
See traceback there.
Why "id" attribute is int?

**Comment by andr1an** [comment]
> Why "id" attribute is int?

It was done for security purposes. The code is validating the value it got the class constructor, especially from an XML representation via `from_xml()` call. I think removing this validation is a bad idea.

Possibly I found out why you are getting this error. Are you trying to call `to_xml()` method from your custom script after getting some records from the API? I never tried this before, I've only called `to_xml()` from `add_record()` method, for those `DNSRecord` objects where `id` is not set.

As a temporary workaround I recommend you to write a custom method for printing `DNSRecord` objects instead of using `to_xml()`. And the permanent solution should be something like this (should be done for all `to_xml` methods):

```diff
diff --git a/nic_api/models.py b/nic_api/models.py
index 2940191..86b5fb2 100644
--- a/nic_api/models.py
+++ b/nic_api/models.py
@@ -203,7 +203,7 @@ class SOARecord(DNSRecord):
         """Returns an XML representation of record object."""
         root = ElementTree.Element("rr")
         if self.id:
-            root.attrib["id"] = self.id
+            root.attrib["id"] = str(self.id)
         ElementTree.SubElement(root, "name").text = self.name
         ElementTree.SubElement(root, "type").text = "SOA"
         _soa = ElementTree.SubElement(root, "soa")
```

If you have a NIC.RU account and some time to write the patch and test it, you're welcome to contribute!

**Comment by AlexNik** [comment]
@andr1an Don't see your previous response)))
Just debug by myself and found the same solution as you.
I've force pushed the changes.

**Comment by andr1an** [comment]
Could you please do the same change for all `to_xml()` methods? There are 9 of them.

**Comment by AlexNik** [comment]
I've done.

@andr1an  What do you think about refactoring: extract the common part of `to_xml()` to `DNSRecord` class to abstract method?

**Comment by andr1an** [comment]
Thank you!

> What do you think about refactoring: extract the common part of `to_xml()` to `DNSRecord` class to abstract method?

Sounds reasonable. Please create a separate issue for this.

**Pull request merged**
